"use client";
import { useEffect, useMemo, useState } from "react";
import { API, APP_URL } from "@/lib/config";
import { copy } from "@/lib/translations";
import { initials, recurrenceOptions } from "@/lib/utils";
import type { User, Reminder, Group, Member, Event, Status, Lang } from "@/types";
import { Brand } from "@/components/common/Brand";
import { Auth } from "@/components/auth/Auth";
import { Dashboard } from "@/components/dashboard/Dashboard";
import { Reminders } from "@/components/reminders/Reminders";
import { Groups } from "@/components/groups/Groups";
import { GroupView } from "@/components/groups/GroupView";
import { EventDetail } from "@/components/events/EventDetail";
import { History } from "@/components/history/History";
import { Emails } from "@/components/emails/Emails";
import { Statistics } from "@/components/statistics/Statistics";
import { Settings } from "@/components/settings/Settings";
import { Help } from "@/components/help/Help";
import { About } from "@/components/about/About";
import { Icon, Button, IconButton, Field, Toggle, Modal } from "@/components/ui";


export default function Home(){
 const [view,setView]=useState("dashboard"); const [user,setUser]=useState<User|null>(null); const [auth,setAuth]=useState<"login"|"register">("login"); const [forgot,setForgot]=useState(false); const [dark,setDark]=useState(false); const [lang,setLang]=useState<Lang>("fr"); const [toast,setToast]=useState(""); const [loading,setLoading]=useState(false);
 const [fullName,setFullName]=useState(""); const [email,setEmail]=useState(""); const [password,setPassword]=useState("");
 const [reminders,setReminders]=useState<Reminder[]>([]); const [groups,setGroups]=useState<Group[]>([]); const [group,setGroup]=useState<Group|null>(null); const [members,setMembers]=useState<Member[]>([]); const [events,setEvents]=useState<Event[]>([]); const [statuses,setStatuses]=useState<Status[]>([]); const [emailLogs,setEmailLogs]=useState<any[]>([]); const [history,setHistory]=useState<any[]>([]); const [activityHistory,setActivityHistory]=useState<any[]>([]);
 const [modal,setModal]=useState<string|null>(null); const [physicalBusy,setPhysicalBusy]=useState(false); const [search,setSearch]=useState(""); const [statusFilter,setStatusFilter]=useState("ALL"); const [mobileOpen,setMobileOpen]=useState(false); const [physicalPayment,setPhysicalPayment]=useState<any>(null); const [editingReminder,setEditingReminder]=useState<Reminder|null>(null); const [editingMember,setEditingMember]=useState<Member|null>(null); const [editingEvent,setEditingEvent]=useState<Event|null>(null); const [selectedEvent,setSelectedEvent]=useState<Event|null>(null);
 const [r,setR]=useState<any>({title:"",description:"",amount:"",payment:false,dueDate:"",recurrence:"NONE",before:"3,1,0",after:"1,3,7",time:"08:00"});
 const [g,setG]=useState<any>({name:"",description:""}); const [m,setM]=useState<any>({name:"",email:""});
 const [ev,setEv]=useState<any>({title:"",amount:"",payment:false,dueDate:"",recurrence:"NONE",before:"3,1,0",after:"1,3,7",time:"08:00",all:true,ids:[]});
 const t=(k:keyof typeof copy.fr)=>copy[lang][k];
 useEffect(()=>{const saved=localStorage.getItem("echeo-user");if(saved)try{setUser(JSON.parse(saved))}catch{};setDark(localStorage.getItem("echeo-theme")==="dark");setLang((localStorage.getItem("echeo-lang") as Lang)||"fr")},[]);
 useEffect(()=>{document.documentElement.classList.toggle("dark",dark);document.body.classList.toggle("darkBody",dark);localStorage.setItem("echeo-theme",dark?"dark":"light")},[dark]);
 useEffect(()=>{localStorage.setItem("echeo-lang",lang)},[lang]);
 useEffect(()=>{if(user){localStorage.setItem("echeo-user",JSON.stringify(user));refresh()}},[user]);
 useEffect(()=>{if(!user)return; if(view==="history") getActivityHistory(); if(view==="emails") getEmails(); if(view==="stats"){getHistory();getActivityHistory();}},[view,user?.id]);
 useEffect(()=>{if(toast){const x=setTimeout(()=>setToast(""),3500);return()=>clearTimeout(x)}},[toast]);
 const req=async(path:string,options:any={})=>{const token=user?.token;let res:Response;try{res=await fetch(`${API}${path}`,{headers:{"Content-Type":"application/json",...(token?{"Authorization":`Bearer ${token}`}:{})},...(options||{})})}catch{throw new Error("Le serveur Échéo est injoignable. Vérifiez qu'il est démarré et que l'URL de l'API est correcte.")}if(res.status===401&&user){localStorage.removeItem("echeo-user");setUser(null);setToast("Votre session a expiré. Veuillez vous reconnecter.");throw new Error("Session expirée")}if(!res.ok)throw new Error(await res.text()||"Erreur serveur");return res.status===204?null:res.json()};
 const getReminders=async()=>{try{setReminders(await req(`/personal-reminders/user/${user!.id}`))}catch{}};
 const getGroups=async()=>{try{setGroups(await req(`/groups/owner/${user!.id}`))}catch{}};
 const getEmails=async()=>{try{setEmailLogs(await req(`/email-logs/user/${user!.id}`))}catch{setEmailLogs([])}};
 const getHistory=async()=>{try{setHistory(await req(`/payment/history/user/${user!.id}`))}catch{setHistory([])}};
 const getActivityHistory=async()=>{try{setActivityHistory(await req(`/reminder-history/user/${user!.id}`))}catch{setActivityHistory([])}};
 const refresh=async()=>{if(user)await Promise.all([getReminders(),getGroups(),getEmails(),getHistory(),getActivityHistory()])};
 const openGroup=async(x:Group)=>{setGroup(x);setView("group");try{const [ms,es]=await Promise.all([req(`/group-members/group/${x.id}`),req(`/group-events/group/${x.id}`)]);setMembers(ms);setEvents(es);if(selectedEvent){const fresh=es.find((e:any)=>e.id===selectedEvent.id);if(fresh)setSelectedEvent(fresh)}}catch{setToast("Impossible de charger le groupe")}};
 const openEvent=async(x:Event)=>{setSelectedEvent(x);try{setStatuses(await req(`/group-events/${x.id}/statuses`))}catch{setStatuses([])}};
 const goBack=()=>{if(selectedEvent){setSelectedEvent(null);return} if(view==="group"){setGroup(null);setView("groups");return} if(view!=="dashboard"){setView("dashboard");return}};
 const navigate=(id:string)=>{setView(id);setSearch("");setStatusFilter("ALL");setMobileOpen(false)};
 const authSubmit=async(e:any)=>{e.preventDefault();setLoading(true);try{const data=await req(`/users/${auth==="login"?"login":"register"}`,{method:"POST",body:JSON.stringify(auth==="login"?{email,password}:{fullName,email,password})});setUser({id:data.id,fullName:data.fullName,email:data.email,token:data.token});setView("dashboard");setToast(auth==="login"?"Bienvenue dans Échéo":"Compte créé avec succès")}catch(err:any){setToast(err.message)}finally{setLoading(false)}};
 const forgotSubmit=async(e:any)=>{e.preventDefault();setLoading(true);try{const msg=await req(`/users/forgot-password`,{method:"POST",body:JSON.stringify({email})});setToast(typeof msg==="string"?msg:t("resetSent"));setForgot(false);setAuth("login")}catch(err:any){setToast(err.message)}finally{setLoading(false)}};
 const resetReminder=()=>setR({title:"",description:"",dueDate:"",recurrence:"NONE",before:"3,1,0",after:"1,3,7",time:"08:00",messageTemplate:""});
 const startEditReminder=(x:Reminder)=>{setEditingReminder(x);const tm=(x.reminderTime||"08:00").toString().slice(0,5);setR({title:x.title||"",description:x.description||"",dueDate:x.dueDate||"",recurrence:x.recurrence||"NONE",before:(x.reminderOffsets||[3,1,0]).join(","),after:(x.reminderAfterOffsets||[1,3,7]).join(","),time:tm,messageTemplate:x.messageTemplate||""});setModal("reminder")};
 const saveReminder=async(e:any)=>{e.preventDefault();if(!r.title.trim()){setToast("Le titre est obligatoire.");return}if(!r.dueDate){setToast("La date d’échéance est obligatoire.");return}const body={user:{id:user!.id},title:r.title,description:r.description,amount:null,dueDate:r.dueDate,recurrence:r.recurrence,recurrenceActive:editingReminder?editingReminder.recurrenceActive!==false:true,reminderOffsets:r.before.split(",").map(Number).filter((n:number)=>!Number.isNaN(n)),reminderAfterOffsets:r.after.split(",").map(Number).filter((n:number)=>!Number.isNaN(n)),reminderTime:r.time,messageTemplate:r.messageTemplate||null};try{if(editingReminder)await req(`/personal-reminders/${editingReminder.id}`,{method:"PUT",body:JSON.stringify(body)});else await req(`/personal-reminders`,{method:"POST",body:JSON.stringify(body)});setModal(null);setEditingReminder(null);resetReminder();await getReminders();setToast(editingReminder?t("updated"):t("created"))}catch(err:any){setToast(err.message)}};
 const deleteReminder=async(id:number)=>{if(!confirm(`${t("confirmDelete")}`))return;try{await req(`/personal-reminders/${id}`,{method:"DELETE"});await getReminders();setToast(t("deleted"))}catch(err:any){setToast(err.message)}};
 const toggleReminderRecurrence=async(r:Reminder)=>{try{await req(`/personal-reminders/${r.id}/recurrence?active=${r.recurrenceActive===false}` ,{method:"PUT"});await getReminders();setToast(r.recurrenceActive===false?t("resumeRecurrence"):t("recurrenceStopped"))}catch(err:any){setToast(err.message)}};
 const markReminderDone=async(id:number)=>{try{await req(`/personal-reminders/${id}/done`,{method:"PUT"});await Promise.all([getReminders(),getActivityHistory()]);setToast(t("done"))}catch(err:any){setToast(err.message)}};
 const createGroup=async(e:any)=>{e.preventDefault();if(!g.name.trim()){setToast("Le nom du groupe est obligatoire.");return}try{await req(`/groups`,{method:"POST",body:JSON.stringify({name:g.name,description:g.description,owner:{id:user!.id}})});setModal(null);setG({name:"",description:""});await getGroups();setToast(`${t("newGroup")} ${t("created")}`)}catch(err:any){setToast(err.message)}};
 const saveMember=async(e:any)=>{e.preventDefault();if(!m.name.trim()){setToast("Le nom du membre est obligatoire.");return}if(!/^\S+@\S+\.\S+$/.test(m.email)){setToast("Veuillez entrer une adresse email valide.");return}try{if(editingMember)await req(`/group-members/${editingMember.id}`,{method:"PUT",body:JSON.stringify({memberName:m.name,memberEmail:m.email})});else await req(`/group-members`,{method:"POST",body:JSON.stringify({group:{id:group!.id},memberName:m.name,memberEmail:m.email})});setModal(null);setEditingMember(null);setM({name:"",email:""});await openGroup(group);setToast(editingMember?t("updated"):t("created"))}catch(err:any){setToast(err.message)}};
 const deleteMember=async(id:number)=>{if(!confirm(`${t("confirmDelete")}`))return;try{await req(`/group-members/${id}`,{method:"DELETE"});await openGroup(group);setToast(t("deleted"))}catch(err:any){setToast(err.message)}};
 const saveEvent=async(e:any)=>{e.preventDefault();if(editingEvent && editingEvent.editable===false){setToast(t("lockedEdit"));return}if(!ev.title.trim()){setToast("Le titre de l’échéance est obligatoire.");return}if(!ev.dueDate){setToast("La date d’échéance est obligatoire.");return}if(ev.payment&&(ev.amount===""||Number(ev.amount)<=0)){setToast("Le montant doit être supérieur à 0.");return}if(!ev.all&&!ev.ids.length){setToast("Sélectionnez au moins un membre");return}const body={group:{id:group!.id},title:ev.title,amount:ev.payment?Number(ev.amount):null,dueDate:ev.dueDate,recurrence:ev.recurrence,recurrenceActive:editingEvent?editingEvent.recurrenceActive!==false:true,reminderOffsets:ev.before.split(",").map(Number).filter((n:number)=>!Number.isNaN(n)),reminderAfterOffsets:ev.after.split(",").map(Number).filter((n:number)=>!Number.isNaN(n)),notifyOwner:ev.notifyOwner!==false,reminderTime:ev.time,messageTemplate:ev.messageTemplate||null};try{let event;if(editingEvent){event=await req(`/group-events/${editingEvent.id}`,{method:"PUT",body:JSON.stringify(body)})}else{event=await req(`/group-events`,{method:"POST",body:JSON.stringify(body)});};const selectedIds=(ev.all?members:members.filter(x=>ev.ids.includes(x.id))).map((x:any)=>x.id);await req(`/group-events/${event.id}/members`,{method:"PUT",body:JSON.stringify(selectedIds)});setModal(null);setEditingEvent(null);await openGroup(group);setToast(editingEvent?t("updated"):t("created"))}catch(err:any){setToast(err.message)}};
 const startEditEvent=(x:Event)=>{setEditingEvent(x);const tm=(x.reminderTime||"08:00").toString().slice(0,5);setEv({title:x.title||"",amount:x.amount??"",payment:x.amount!=null,dueDate:x.dueDate||"",recurrence:x.recurrence||"NONE",before:(x.reminderOffsets||[3,1,0]).join(","),after:(x.reminderAfterOffsets||[1,3,7]).join(","),time:tm,notifyOwner:x.notifyOwner!==false,messageTemplate:x.messageTemplate||"",all:true,ids:members.map((m:any)=>m.id)});setModal("event")};
 const deleteEvent=async(id:number)=>{if(!confirm(`${t("confirmDelete")}`))return;try{await req(`/group-events/${id}`,{method:"DELETE"});setSelectedEvent(null);await openGroup(group);setToast(t("deleted"))}catch(err:any){setToast(err.message)}};
 const toggleEventRecurrence=async(event:Event)=>{try{await req(`/group-events/${event.id}/recurrence?active=${event.recurrenceActive===false}`,{method:"PUT"});if(group)await openGroup(group);if(selectedEvent){const fresh=events.find((e:any)=>e.id===event.id);if(fresh)setSelectedEvent({...fresh,recurrenceActive:event.recurrenceActive===false});}setToast(event.recurrenceActive===false?t("resumeRecurrence"):t("recurrenceStopped"))}catch(err:any){setToast(err.message)}};
 const deleteGroup=async(id:number)=>{if(!confirm(`${t("confirmDelete")}`))return;try{await req(`/groups/${id}`,{method:"DELETE"});if(group?.id===id){setGroup(null);setMembers([]);setEvents([]);setView("groups")}await getGroups();setToast(t("deleted"))}catch(err:any){setToast(err.message)}};
 const generateLink=async(type:string,id:number,memberId?:number)=>{try{const data=await req(`/payment/generate`,{method:"POST",body:JSON.stringify({reminderType:type,reminderId:id,memberId:memberId||null})});const link=`${APP_URL}/pay/${data.token}`;try{await navigator.clipboard?.writeText(link)}catch{};setToast(`${t("copied")} — ${link}`)}catch(err:any){setToast(err.message)}};
 const recordPhysicalPayment=async()=>{if(physicalBusy)return;if(!physicalPayment||physicalPayment.amount===""){setToast("Saisissez le montant reçu.");return}if(Number(physicalPayment.amount)<=0){setToast("Le montant reçu doit être supérieur à 0.");return}setPhysicalBusy(true);try{const out=await req(`/payment/physical`,{method:"POST",body:JSON.stringify({reminderType:physicalPayment.type,reminderId:physicalPayment.reminderId,memberId:physicalPayment.memberId||null,amount:Number(physicalPayment.amount)})});const paidEventId=physicalPayment.reminderId;const wasGroup=physicalPayment.type==="GROUP";setPhysicalPayment(null);if(wasGroup)setSelectedEvent(null);await Promise.all([getHistory(),getActivityHistory(),getEmails()]);if(group)await openGroup(group);else await getReminders();setToast(out.message||t("created"));}catch(err:any){setToast(err.message)}finally{setPhysicalBusy(false);}};
 const deleteHistory=async(id:number)=>{if(!confirm(`${t("confirmDelete")}`))return;try{await req(`/payment/history/${id}`,{method:"DELETE"});await getHistory();setToast(t("deleted"))}catch(err:any){setToast(err.message)}};
 const deleteActivity=async(id:number)=>{if(!confirm(`${t("confirmDelete")}`))return;try{await req(`/reminder-history/${id}`,{method:"DELETE"});await getActivityHistory();setToast(t("deleted"))}catch(err:any){setToast(err.message)}};
 const deleteEmail=async(id:number)=>{if(!confirm(`${t("confirmDelete")}`))return;try{await req(`/email-logs/${id}`,{method:"DELETE"});await getEmails();setToast(t("deleted"))}catch(err:any){setToast(err.message)}};
  const markMemberDone=async(statusId:number)=>{try{await req(`/group-events/status/${statusId}/done`,{method:"PUT"});await getActivityHistory();if(selectedEvent){setStatuses(await req(`/group-events/${selectedEvent.id}/statuses`));}if(group)await openGroup(group);setToast(t("memberDone"));}catch(err:any){setToast(err.message)}};
  const clearAllHistory=async()=>{if(!activityHistory.length&&!history.length)return;if(!confirm(`${t("clearHistory")} ?`))return;try{await Promise.all([req(`/reminder-history/user/${user!.id}`,{method:"DELETE"}),...history.map((h:any)=>req(`/payment/history/${h.id}`,{method:"DELETE"}))]);await Promise.all([getActivityHistory(),getHistory()]);setToast(t("deleted"));}catch(err:any){setToast(err.message)}};
  const clearAllEmails=async()=>{if(!emailLogs.length)return;if(!confirm(`${t("clearEmails")} ?`))return;try{await Promise.all(emailLogs.map((x:any)=>req(`/email-logs/${x.id}`,{method:"DELETE"})));await getEmails();setToast(t("deleted"));}catch(err:any){setToast(err.message)}};
 const stats=useMemo(()=>{const today=new Date().toISOString().slice(0,10);return {expected:history.reduce((s,x)=>s+(Number(x.expectedAmount)||0),0),overdue:reminders.filter(x=>!x.paid&&!x.isPaid&&x.dueDate<today).length,upcoming:reminders.filter(x=>!x.paid&&!x.isPaid&&x.dueDate>=today).length,total:history.reduce((s,x)=>s+(Number(x.amountPaid)||0),0),paid:reminders.filter(x=>x.paid||x.isPaid).length,partial:history.filter(x=>x.status==="PARTIAL").length,overpaid:history.filter(x=>x.status==="OVERPAID").length,completePayments:history.filter(x=>x.status==="COMPLETE").length}},[reminders,history]);
 const logout=async()=>{try{await req("/users/logout",{method:"POST"})}catch{} localStorage.removeItem("echeo-user");setUser(null);setView("dashboard")};
 if(!user)return <Auth auth={auth} setAuth={setAuth} forgot={forgot} setForgot={setForgot} fullName={fullName} setFullName={setFullName} email={email} setEmail={setEmail} password={password} setPassword={setPassword} submit={authSubmit} forgotSubmit={forgotSubmit} loading={loading} t={t}/>;
 const title=view==="dashboard"?`${lang==="fr"?"Bonjour":"Hello"}, ${user.fullName.split(" ")[0]}`:view==="group"?(group?.name||t("groups")):(copy[lang][view as keyof typeof copy.fr]||t("overview"));
 const nav=[[
  "dashboard","home",t("overview")],["reminders","clock",t("reminders")],["groups","users",t("groups")],["history","history",t("history")],["emails","mail",t("emails")],["stats","chart",t("stats")],["settings","settings",t("settings")],["help","help",t("help")],["about","info",t("about")]
 ] as string[][];
 return <div className="appShell"><aside className="sidebar"><Brand/><nav>{nav.map(([id,ic,label])=><button key={id} onClick={()=>navigate(id)} className={`navItem ${view===id?"active":""}`}><Icon name={ic}/><span>{label}</span></button>)}</nav><div className="sideUser"><div className="avatar">{initials(user.fullName)}</div><div className="min0"><b>{user.fullName}</b><small>{user.email}</small></div><button onClick={logout} title={t("logout")}><Icon name="arrowRight" size={16}/></button></div></aside>
 <main className="main"><header className="topbar"><div className="topLeft"><IconButton name="menu" onClick={()=>setMobileOpen(true)} title={t("menu")}/>{view!=="dashboard"&&<IconButton name="arrowLeft" onClick={goBack} title={t("back")}/>}<div><span className="eyebrow">Échéo</span><h1>{title}</h1></div></div><div className="topActions"><IconButton name={dark?"sun":"moon"} onClick={()=>setDark(!dark)} title={dark?t("light"):t("dark")}/><button className="avatar" onClick={()=>navigate("settings")} title={t("settings")}>{initials(user.fullName)}</button></div></header>
 <div className="content">{view==="dashboard"&&<Dashboard stats={stats} reminders={reminders} groups={groups} setView={setView} setModal={setModal} openGroup={openGroup} t={t}/>} {view==="reminders"&&<Reminders reminders={reminders} search={search} setSearch={setSearch} statusFilter={statusFilter} setStatusFilter={setStatusFilter} setModal={()=>{setEditingReminder(null);resetReminder();setModal("reminder")}} startEdit={startEditReminder} deleteReminder={deleteReminder} markDone={markReminderDone} toggleRecurrence={toggleReminderRecurrence} t={t}/>} {view==="groups"&&<Groups groups={groups} search={search} setSearch={setSearch} setModal={()=>{setEditingMember(null);setModal("group")}} openGroup={openGroup} deleteGroup={deleteGroup} t={t}/>} {view==="group"&&group&&<GroupView group={group} members={members} events={events} setModal={setModal} setM={setM} setEditingMember={setEditingMember} setEditingEvent={setEditingEvent} setEv={setEv} openEvent={openEvent} deleteMember={deleteMember} deleteEvent={deleteEvent} t={t}/>} {view==="history"&&<History history={activityHistory} search={search} setSearch={setSearch} deleteHistory={deleteActivity} clearAll={clearAllHistory} t={t}/>} {view==="emails"&&<Emails logs={emailLogs} search={search} setSearch={setSearch} deleteEmail={deleteEmail} clearAll={clearAllEmails} ownEmail={user?.email} t={t}/>} {view==="stats"&&<Statistics stats={stats} history={history} reminders={reminders} groups={groups} t={t}/>} {view==="settings"&&<Settings dark={dark} setDark={setDark} lang={lang} setLang={setLang} user={user} t={t}/>} {view==="help"&&<Help t={t}/>} {view==="about"&&<About t={t}/>}</div></main>
 {mobileOpen&&<div className="drawerOverlay" onClick={()=>setMobileOpen(false)}><aside className="mobileDrawer" onClick={e=>e.stopPropagation()}><div className="drawerHead"><Brand/><IconButton name="x" onClick={()=>setMobileOpen(false)} title={t("close")}/></div><nav>{nav.map(([id,ic,label])=><button key={id} onClick={()=>navigate(id)} className={`navItem ${view===id?"active":""}`}><Icon name={ic}/><span>{label}</span></button>)}</nav><div className="drawerUser"><div className="avatar">{initials(user.fullName)}</div><div className="min0"><b>{user.fullName}</b><small>{user.email}</small></div></div><Button kind="secondary" onClick={logout}>{t("logout")}</Button></aside></div>}
 {toast&&<div className="toast">{toast}</div>}
 {modal==="reminder"&&<Modal title={editingReminder?t("edit"):t("newReminder")} close={()=>{setModal(null);setEditingReminder(null)}}><form onSubmit={saveReminder} className="formGrid"><Field label={t("title")}><input required className="input" value={r.title} onChange={e=>setR({...r,title:e.target.value})}/></Field><Field label={t("description")}><textarea className="input textarea" value={r.description} onChange={e=>setR({...r,description:e.target.value})}/></Field><div className="two"><Field label={t("dueDate")}><input required type="date" className="input" value={r.dueDate} onChange={e=>setR({...r,dueDate:e.target.value})}/></Field><Field label={t("time")}><input type="time" className="input" value={r.time} onChange={e=>setR({...r,time:e.target.value})}/></Field></div><Field label={t("recurrence")}><select className="input" value={r.recurrence} onChange={e=>setR({...r,recurrence:e.target.value})}>{["NONE","DAILY","WEEKLY","MONTHLY","YEARLY"].map(x=><option key={x} value={x}>{t(recurrenceOptions(x) as any)}</option>)}</select></Field><div className="two"><Field label={t("before")} hint="Ex. 3,1,0"><input className="input" value={r.before} onChange={e=>setR({...r,before:e.target.value})}/></Field><Field label={t("after")} hint="Ex. 1,3,7"><input className="input" value={r.after} onChange={e=>setR({...r,after:e.target.value})}/></Field></div><Field label={t("messageTemplate")} hint="Optionnel — message personnalisé du rappel email."><textarea className="input textarea" value={r.messageTemplate||""} onChange={e=>setR({...r,messageTemplate:e.target.value})}/></Field><div className="modalActions"><Button kind="secondary" onClick={()=>setModal(null)}>{t("cancel")}</Button><Button type="submit">{t("save")}</Button></div></form></Modal>}
 {modal==="group"&&<Modal title={t("newGroup")} close={()=>setModal(null)}><form onSubmit={createGroup} className="formGrid"><Field label={t("name")}><input required className="input" value={g.name} onChange={e=>setG({...g,name:e.target.value})}/></Field><Field label={t("description")}><textarea className="input textarea" value={g.description} onChange={e=>setG({...g,description:e.target.value})}/></Field><div className="modalActions"><Button kind="secondary" onClick={()=>setModal(null)}>{t("cancel")}</Button><Button type="submit">{t("create")}</Button></div></form></Modal>}
 {modal==="member"&&<Modal title={editingMember?t("edit"):t("addMember")} close={()=>setModal(null)}><form onSubmit={saveMember} className="formGrid"><Field label={t("name")}><input required className="input" value={m.name} onChange={e=>setM({...m,name:e.target.value})}/></Field><Field label={t("emailReceive")}><input required type="email" className="input" value={m.email} onChange={e=>setM({...m,email:e.target.value})}/></Field><div className="modalActions"><Button kind="secondary" onClick={()=>setModal(null)}>{t("cancel")}</Button><Button type="submit">{t("save")}</Button></div></form></Modal>}
 {modal==="event"&&<Modal title={editingEvent?t("edit"):t("newEvent")} close={()=>setModal(null)}><form onSubmit={saveEvent} className="formGrid"><Field label={t("title")}><input required className="input" value={ev.title} onChange={e=>setEv({...ev,title:e.target.value})}/></Field><div className="two"><Field label={t("dueDate")}><input required type="date" className="input" value={ev.dueDate} onChange={e=>setEv({...ev,dueDate:e.target.value})}/></Field><Field label={t("time")}><input type="time" className="input" value={ev.time} onChange={e=>setEv({...ev,time:e.target.value})}/></Field></div><Toggle checked={ev.payment} setChecked={(v)=>setEv({...ev,payment:v})} label={t("payment")}/>{ev.payment&&<Field label={t("amount")}><input required type="number" min="0" className="input" value={ev.amount} onChange={e=>setEv({...ev,amount:e.target.value})}/></Field>}<Field label={t("recurrence")}><select className="input" value={ev.recurrence} onChange={e=>setEv({...ev,recurrence:e.target.value})}>{["NONE","DAILY","WEEKLY","MONTHLY","YEARLY"].map(x=><option key={x} value={x}>{t(recurrenceOptions(x) as any)}</option>)}</select></Field><div className="two"><Field label={t("before")}><input className="input" value={ev.before} onChange={e=>setEv({...ev,before:e.target.value})}/></Field><Field label={t("after")}><input className="input" value={ev.after} onChange={e=>setEv({...ev,after:e.target.value})}/></Field></div><div><label className="label">{t("membersConcerned")}</label><label className="checkRow"><input type="checkbox" checked={ev.all} onChange={e=>setEv({...ev,all:e.target.checked,ids:e.target.checked?members.map((x:any)=>x.id):[]})}/>{t("wholeGroup")}</label>{!ev.all&&members.map((x:any)=><label key={x.id} className="checkRow"><input type="checkbox" checked={ev.ids.includes(x.id)} onChange={()=>setEv({...ev,ids:ev.ids.includes(x.id)?ev.ids.filter((i:number)=>i!==x.id):[...ev.ids,x.id]})}/>{x.memberName}<small>{x.memberEmail}</small></label>)} </div><Field label={t("messageTemplate")}><textarea className="input textarea" value={ev.messageTemplate||""} onChange={e=>setEv({...ev,messageTemplate:e.target.value})}/></Field><Toggle checked={ev.notifyOwner!==false} setChecked={(v)=>setEv({...ev,notifyOwner:v})} label={t("notifyOwner")}/><div className="modalActions"><Button kind="secondary" onClick={()=>setModal(null)}>{t("cancel")}</Button><Button type="submit">{t("save")}</Button></div></form></Modal>}
 {selectedEvent&&<EventDetail event={selectedEvent} statuses={statuses} close={()=>setSelectedEvent(null)} edit={()=>{if(selectedEvent.editable===false){setToast(t("lockedEdit"));return}startEditEvent(selectedEvent);setSelectedEvent(null)}} deleteEvent={deleteEvent} generateLink={generateLink} physicalPayment={(memberId:number)=>setPhysicalPayment({type:"GROUP",reminderId:selectedEvent.id,memberId,amount:""})} markMemberDone={markMemberDone} toggleRecurrence={toggleEventRecurrence} t={t}/>}
 {physicalPayment&&<Modal title={t("physicalPayment")} close={()=>setPhysicalPayment(null)}><div className="stack"><div className="infoBox"><small>{t("paymentMethod")}</small><b>{t("physical")}</b></div><Field label={t("receivedAmount")}><input autoFocus type="number" min="0" className="input" value={physicalPayment.amount} onChange={e=>setPhysicalPayment({...physicalPayment,amount:e.target.value})}/></Field><div className="modalActions"><Button kind="secondary" onClick={()=>setPhysicalPayment(null)}>{t("cancel")}</Button><Button onClick={recordPhysicalPayment} disabled={physicalBusy}>{physicalBusy?"…":t("registerPayment")}</Button></div></div></Modal>} 
 </div>
}
