import type { Lang } from "@/types";

export const copy = 
{
  fr: {
    overview:"Vue d’ensemble", reminders:"Mes rappels", groups:"Mes groupes", history:"Historique", emails:"Messages envoyés", stats:"Statistiques", settings:"Paramètres", help:"Centre d’aide", about:"À propos",
    back:"Retour", logout:"Se déconnecter", light:"Mode clair", dark:"Mode sombre", language:"Langue", french:"Français", english:"English",
    newReminder:"Nouveau rappel", addReminder:"Ajouter un rappel", newGroup:"Nouveau groupe", addMember:"Ajouter un membre", newEvent:"Nouvelle échéance", edit:"Modifier", remove:"Supprimer", save:"Enregistrer", cancel:"Annuler", close:"Fermer", menu:"Menu", physicalPayment:"Paiement physique", receivedAmount:"Montant reçu", registerPayment:"Enregistrer le paiement", paymentMethod:"Mode de paiement", online:"En ligne", physical:"Physique", messageDetails:"Voir le message", recipient:"Destinataire", subject:"Objet", message:"Message", ownerReminder:"Rappel propriétaire", notifyOwner:"Notifier aussi le propriétaire", messageTemplate:"Message envoyé",
    title:"Titre", description:"Description", dueDate:"Date d’échéance", time:"Heure des rappels", amount:"Montant attendu", payment:"Cette échéance concerne un paiement", recurrence:"Répétition", stopRecurrence:"Arrêter la répétition", resumeRecurrence:"Reprendre la répétition", recurrenceStopped:"Répétition arrêtée", none:"Aucune", daily:"Chaque jour", weekly:"Chaque semaine", monthly:"Chaque mois", yearly:"Chaque année", before:"Rappels avant (jours)", after:"Relances après (jours)", done:"Fait", markDone:"Marquer comme fait", upcoming:"À venir", overdue:"En retard", pending:"En attente", paid:"Réglé", partial:"Partiel",
    dashboardIntro:"Votre espace personnel est prêt.", active:"Rappels actifs", planned:"Montants prévus", completed:"Terminés", next:"Prochaines échéances", all:"Tout voir", groupSpaces:"Vos espaces collaboratifs", firstGroup:"Créez votre premier groupe.", firstReminder:"Aucun rappel pour le moment.",
    name:"Nom", email:"Email", emailReceive:"Email de réception", members:"Membres", membersConcerned:"Membres concernés", wholeGroup:"Tout le groupe", selectMembers:"Sélectionner", groupDue:"Échéances du groupe", noGroupDue:"Aucune échéance de groupe.", noMembers:"Ajoutez un membre.",
    create:"Créer", created:"créé", deleted:"supprimé", updated:"modifié", sent:"Envoyé", failed:"Échec", messagesEmpty:"Les messages envoyés apparaîtront ici.", paymentLink:"Générer le lien de paiement", copied:"Lien de paiement copié", paymentNote:"Paiement facultatif — vous pourrez envoyer un lien de paiement.",
    statsTitle:"Statistiques", totalReminders:"Total des rappels", totalAmount:"Montant total", completedPayments:"Paiements réglés", overdueCount:"Échéances en retard", partialPayments:"Paiements partiels", surplusPayments:"Paiements avec surplus",
    settingsTitle:"Paramètres", appearance:"Apparence", appearanceSub:"Une interface confortable en clair comme en sombre.", helpTitle:"Questions fréquentes", aboutTitle:"À propos", noPayments:"Aucun paiement enregistré pour le moment.", historyDone:"Rappel terminé", historyPayment:"Paiement enregistré", historyGroup:"Échéance de groupe", historyPersonal:"Rappel personnel", statusDone:"Terminé", statusPartial:"Partiel", statusPartialOverdue:"Partiel · en retard", statusOverpaid:"Surplus", statusInProgress:"En cours", statusPending:"En attente", statusOverdue:"En retard", lockedEdit:"Cette échéance ne peut plus être modifiée car elle a déjà été réalisée ou réglée.", remaining:"Reste à payer", received:"Reçu", totalReceived:"Total reçu", surplus:"Surplus", paymentState:"État du paiement",
    login:"Se connecter", register:"Créer mon compte", forgotPassword:"Mot de passe oublié ?", forgotTitle:"Récupérer mon mot de passe", sendReset:"Envoyer le lien", backLogin:"Retour à la connexion", resetSent:"Si le compte existe, un lien de récupération a été envoyé.", welcomeBack:"Ravi de vous revoir", welcome:"Bienvenue sur Échéo", password:"Mot de passe", fullName:"Nom complet", createAccount:"Créer un compte", alreadyAccount:"Déjà un compte ? Se connecter", noAccount:"Pas encore de compte ? Créer un compte",
    confirmDelete:"Confirmer la suppression ?", deleteAll:"Tout supprimer", noData:"Aucune donnée", refresh:"Actualiser", search:"Rechercher", searchReminders:"Rechercher un rappel...", searchGroups:"Rechercher un groupe...", searchHistory:"Rechercher dans l’historique...", searchEmails:"Rechercher un message, destinataire...", noResults:"Aucun résultat", allStatuses:"Tous les états",
    markMemberDone:"Marquer comme fait", memberDone:"Membre marqué comme fait",
    aboutMission:"Échéo vous aide à ne plus oublier vos échéances personnelles et collectives. Rappels automatiques, suivi des paiements et historique clair.",
    aboutVersion:"Version 1.0", aboutFeatures:"Fonctionnalités", aboutRemindersDesc:"Rappels personnels avec répétition et offsets avant / après.", aboutGroupsDesc:"Groupes, membres et échéances partagées avec notifications.", aboutPaymentsDesc:"Liens de paiement simulés, paiements physiques et rapport attendu / reçu.", aboutSecurity:"Les paiements sont en simulation tant qu’aucune API bancaire n’est branchée.",
    paymentBreakdown:"Répartition des paiements", recentOps:"Dernières opérations", collectionRate:"Taux de règlement", overdueRate:"Taux de retard", avgPayment:"Paiement moyen", expectedVsReceived:"Attendu vs reçu",
    clearHistory:"Vider l’historique", clearEmails:"Vider les messages", open:"Ouvrir", actions:"Actions",
  },
  en: {
    overview:"Overview", reminders:"My reminders", groups:"My groups", history:"History", emails:"Sent messages", stats:"Statistics", settings:"Settings", help:"Help center", about:"About",
    back:"Back", logout:"Log out", light:"Light mode", dark:"Dark mode", language:"Language", french:"French", english:"English",
    newReminder:"New reminder", addReminder:"Add reminder", newGroup:"New group", addMember:"Add member", newEvent:"New due date", edit:"Edit", remove:"Delete", save:"Save", cancel:"Cancel", close:"Close", menu:"Menu", physicalPayment:"Physical payment", receivedAmount:"Amount received", registerPayment:"Record payment", paymentMethod:"Payment method", online:"Online", physical:"Physical", messageDetails:"View message", recipient:"Recipient", subject:"Subject", message:"Message", ownerReminder:"Owner reminder", notifyOwner:"Also notify the owner", messageTemplate:"Message sent",
    title:"Title", description:"Description", dueDate:"Due date", time:"Reminder time", amount:"Expected amount", payment:"This due date concerns a payment", recurrence:"Repeat", stopRecurrence:"Stop recurrence", resumeRecurrence:"Resume recurrence", recurrenceStopped:"Recurrence stopped", none:"None", daily:"Every day", weekly:"Every week", monthly:"Every month", yearly:"Every year", before:"Reminders before (days)", after:"Follow-ups after (days)", done:"Done", markDone:"Mark as done", upcoming:"Upcoming", overdue:"Overdue", pending:"Pending", paid:"Paid", partial:"Partial",
    dashboardIntro:"Your personal space is ready.", active:"Active reminders", planned:"Planned amounts", completed:"Completed", next:"Upcoming due dates", all:"View all", groupSpaces:"Your collaborative spaces", firstGroup:"Create your first group.", firstReminder:"No reminders yet.",
    name:"Name", email:"Email", emailReceive:"Recipient email", members:"Members", membersConcerned:"Members concerned", wholeGroup:"Whole group", selectMembers:"Select", groupDue:"Group due dates", noGroupDue:"No group due dates.", noMembers:"Add a member.",
    create:"Create", created:"created", deleted:"deleted", updated:"updated", sent:"Sent", failed:"Failed", messagesEmpty:"Sent messages will appear here.", paymentLink:"Generate payment link", copied:"Payment link copied", paymentNote:"Optional payment — you can send a payment link.",
    statsTitle:"Statistics", totalReminders:"Total reminders", totalAmount:"Total amount", completedPayments:"Completed payments", overdueCount:"Overdue due dates", partialPayments:"Partial payments", surplusPayments:"Overpaid payments",
    settingsTitle:"Settings", appearance:"Appearance", appearanceSub:"A comfortable interface in light and dark mode.", helpTitle:"Frequently asked questions", aboutTitle:"About", noPayments:"No payment recorded yet.", historyDone:"Reminder completed", historyPayment:"Payment recorded", historyGroup:"Group due date", historyPersonal:"Personal reminder", statusDone:"Completed", statusPartial:"Partial", statusPartialOverdue:"Partial · overdue", statusOverpaid:"Overpaid", statusInProgress:"In progress", statusPending:"Pending", statusOverdue:"Overdue", lockedEdit:"This due date can no longer be edited because it has already been completed or settled.", remaining:"Remaining", received:"Received", totalReceived:"Total received", surplus:"Surplus", paymentState:"Payment status",
    login:"Log in", register:"Create account", forgotPassword:"Forgot password?", forgotTitle:"Recover my password", sendReset:"Send reset link", backLogin:"Back to login", resetSent:"If the account exists, a recovery link has been sent.", welcomeBack:"Welcome back", welcome:"Welcome to Échéo", password:"Password", fullName:"Full name", createAccount:"Create an account", alreadyAccount:"Already have an account? Log in", noAccount:"No account yet? Create one",
    confirmDelete:"Confirm deletion?", deleteAll:"Delete all", noData:"No data", refresh:"Refresh", search:"Search", searchReminders:"Search a reminder...", searchGroups:"Search a group...", searchHistory:"Search history...", searchEmails:"Search a message, recipient...", noResults:"No results", allStatuses:"All statuses",
    markMemberDone:"Mark as done", memberDone:"Member marked as done",
    aboutMission:"Échéo helps you never miss personal and group due dates. Automatic reminders, payment tracking and a clear history.",
    aboutVersion:"Version 1.0", aboutFeatures:"Features", aboutRemindersDesc:"Personal reminders with recurrence and before/after offsets.", aboutGroupsDesc:"Groups, members and shared due dates with notifications.", aboutPaymentsDesc:"Simulated payment links, physical payments and expected vs received reports.", aboutSecurity:"Payments remain simulated until a real banking API is connected.",
    paymentBreakdown:"Payment breakdown", recentOps:"Recent operations", collectionRate:"Settlement rate", overdueRate:"Overdue rate", avgPayment:"Average payment", expectedVsReceived:"Expected vs received",
    clearHistory:"Clear history", clearEmails:"Clear messages", open:"Open", actions:"Actions",
  }
} as const;
